image: op-gitlab.howest.be:4567/docker-registry/project:2020.project-I

stages:
  - build
  - qa
  - deploy

before_script:
  - chmod +x gradlew
  - ln -s "$MAVEN_LOCAL" ".m2"

build-jar:
  stage: build
  only: 
    - master
  except:
    changes:
      - documents/**/*
  script:
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/

sonarqube:
  variables:
    openApi3Spec: http://172.18.18.201/alhambra-api-spec/alhambra-spec.yaml
  stage: qa
  except:
    changes:
      - documents/**/*
  script: ./gradlew sonarqube
  
deploy:
  image: debian:latest
  before_script:
    - echo "we don't need gradle or maven anymore"
  stage: deploy
  only:
    - master
  except:
    changes:
      - documents/**/*
  script:
    - apt update -y && apt install -y software-properties-common rename
    - cd build/libs/
    - rename 's/.*\.jar$/alhambra.jar/' *.jar
    - 'which ssh-agent || apt install -y openssh-client cowsay'
    - PATH="$PATH:/usr/games"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 172.18.18.201 >> ~/.ssh/known_hosts
    - scp -q alhambra.jar gitlab-runner@172.18.18.201:"/opt/group-${CI_PROJECT_NAMESPACE:(-2)}/alhambra.jar"
    - ssh gitlab-runner@172.18.18.201 sudo systemctl restart group-${CI_PROJECT_NAMESPACE:(-2)}
    - systemctl -H gitlab-runner@172.18.18.201 status group-${CI_PROJECT_NAMESPACE:(-2)}
  environment: production
